### ISSUE TITLE
miniconda and singularity: Function Not Implemented

### ISSUE THREAD

**Issue by jdkent** [ReproNim/neurodocker#314]
Keeping reference of this issue for future wanderers:
```
[30094] Failed to execute script entry_point
Traceback (most recent call last):
  File "entry_point.py", line 59, in <module>
  File "concurrent/futures/process.py", line 556, in __init__
  File "concurrent/futures/process.py", line 165, in __init__
  File "multiprocessing/queues.py", line 42, in __init__
  File "multiprocessing/context.py", line 67, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 59, in __init__
OSError: [Errno 38] Function not implemented
ABORT: Aborting with RETVAL=255
```

ref1: ContinuumIO/anaconda-issues#11163
ref2: sylabs/singularity#875

solution(s): 
- use an older miniconda installer: version 4.6.14
- add `-B /run/shm:/run/shm` when running the singularity container (not a good solution when trying to install miniconda

The singularity issue for the miniconda test appears to be related to ContinuumIO/anaconda-issues#11163

_Originally posted by @jdkent in https://github.com/ReproNim/neurodocker/pull/306#issuecomment-572395360_

**Comment by djarecka** [comment]
if this is still relevant please reopen
