### ISSUE TITLE
chromo OS unable to open jypiter notebook OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by B185114-2020** [ReproNim/neurodocker#376]
Hello, I am quite desperate. I have been hours trying to open Jupyter notebook and it does not work. I tried reinstalling conda and all. A while ago I was able to open it but the python packages that I normally used could not be imported. I closed it and reinstall the packages and now AGAIN I cannot open. Please help!

```
(base) 00:29:23fatimitagonzalez:~$ jupyter notebook
Traceback (most recent call last):
  File "/home/fatimitagonzalez/anaconda_u/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/home/fatimitagonzalez/anaconda_u/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/fatimitagonzalez/anaconda_u/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</home/fatimitagonzalez/anaconda_u/lib/python3.7/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/home/fatimitagonzalez/anaconda_u/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/fatimitagonzalez/anaconda_u/lib/python3.7/site-packages/notebook/notebookapp.py", line 1769, in initialize
    self.init_webapp()
  File "/home/fatimitagonzalez/anaconda_u/lib/python3.7/site-packages/notebook/notebookapp.py", line 1490, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/home/fatimitagonzalez/anaconda_u/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/fatimitagonzalez/anaconda_u/lib/python3.7/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```

i have a Chromebook. 
Chrome OS. crostini

**Comment by kaczmarj** [comment]
@B185114-2020 - please try

```
jupyter-notebook --ip=0.0.0.0
```

this is likely related to https://github.com/ReproNim/neurodocker/issues/82#issuecomment-324898673

**Comment by B185114-2020** [comment]
Hello, thank you for your answer. In the terminal the following appears:
`jupyter-notebook --ip=0.0.0.0

[I 18:24:39.342 NotebookApp] JupyterLab extension loaded from /home/fatimitagonzalez/anaconda_u/lib/python3.7/site-packages/jupyterlab
[I 18:24:39.342 NotebookApp] JupyterLab application directory is /home/fatimitagonzalez/anaconda_u/share/jupyter/lab
[I 18:24:39.357 NotebookApp] Serving notebooks from local directory: /home/fatimitagonzalez
[I 18:24:39.357 NotebookApp] The Jupyter Notebook is running at:
[I 18:24:39.357 NotebookApp] http://penguin:8888/?token=55ab07a7cf2a9fd33ae459af5ebd48a4a56a4a056f579c34
[I 18:24:39.358 NotebookApp]  or http://127.0.0.1:8888/?token=55ab07a7cf2a9fd33ae459af5ebd48a4a56a4a056f579c34
[I 18:24:39.358 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:24:39.617 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/fatimitagonzalez/.local/share/jupyter/runtime/nbserver-1104-open.html
    Or copy and paste one of these URLs:
        http://penguin:8888/?token=55ab07a7cf2a9fd33ae459af5ebd48a4a56a4a056f579c34
     or http://127.0.0.1:8888/?token=55ab07a7cf2a9fd33ae459af5ebd48a4a56a4a056f579c34
`

And automatically a new window opened and it has been loading for ages... the URL is: file:///media/fuse/crostini_76a1302875028e63c778c5565388035ba0357640_termina_penguin/.local/share/jupyter/runtime/nbserver-1104-open.html

**Comment by B185114-2020** [comment]
Hi, it works! thank you. Can you tell me what was the problem? cheers!

**Comment by kaczmarj** [comment]
https://github.com/ReproNim/neurodocker/issues/82#issuecomment-324898673 has some discussion about why this might be. I honestly don't remember why. and i don't know if i ever knew!
