### ISSUE TITLE
Freesurfer 7.1.1 Seems to fail

### ISSUE THREAD

**Issue by N-Accumbens** [ReproNim/neurodocker#399]
The readme says that freesurfer 7.1.1 should be supported, but it seems like this is not actually the case in neurodocker 0.7.0?

Here's what I ran
```
sudo docker run --rm repronim/neurodocker:0.7.0 generate singularity \
        --base debian:buster \
        --pkg-manager=apt \
        --freesurfer version=7.1.1 method=binaries --copy /usr/local/freesurfer/license.txt \
                 /opt/free-surfer-7.1.1
```

Here's what I got
```
# Generated by: Neurodocker version 0.7.0+0.gdc97516.dirty
# Latest release: Neurodocker version 0.7.0
[NEURODOCKER 2021-05-23 15:41:53,732 ERROR]: Failed to instantiate <class 'neurodocker.interfaces.interfaces.FreeSurfer'>: URL not found for version '7.1.1'. Valid versions are 6.0.1, 6.0.0, 6.0.0-min
Traceback (most recent call last):
  File "/usr/bin/neurodocker", line 11, in <module>
    load_entry_point('neurodocker', 'console_scripts', 'neurodocker')()
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 429, in main
    subparser_functions[namespace.subsubparser_name](namespace)
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 373, in generate
    print(recipe_obj.render())
  File "/opt/neurodocker/neurodocker/generators/singularity.py", line 115, in render
    self._fill_parts()
  File "/opt/neurodocker/neurodocker/generators/singularity.py", line 171, in _fill_parts
    interface = impl(pkg_manager=pkg_man, **params)
  File "/opt/neurodocker/neurodocker/interfaces/interfaces.py", line 103, in __init__
    super().__init__(self._name, *args, **kwargs)
  File "/opt/neurodocker/neurodocker/interfaces/_base.py", line 204, in __init__
    self.binaries_url = self._resolver.binaries_url(self._version)
  File "/opt/neurodocker/neurodocker/interfaces/_base.py", line 170, in binaries_url
    self.check_binaries_has_url(version)
  File "/opt/neurodocker/neurodocker/interfaces/_base.py", line 166, in check_binaries_has_url
    .format(version, ', '.join(valid_vers))
ValueError: URL not found for version '7.1.1'. Valid versions are 6.0.1, 6.0.0, 6.0.0-min
```

**Comment by kaczmarj** [comment]
Can you please try with the docker image `repronim/neurodocker:master`? We added freesurfer 7.1.1 after neurodocker 0.7.0, but we haven't released a new version of neurodocker yet.

**Comment by N-Accumbens** [comment]
> Can you please try with the docker image `repronim/neurodocker:master`? We added freesurfer 7.1.1 after neurodocker 0.7.0, but we haven't released a new version of neurodocker yet.

This solves it
