### ISSUE TITLE
Minify error : Not running in a Docker Container

### ISSUE THREAD

**Issue by axlbonnet** [ReproNim/neurodocker#405]
I have an issue minifying my neurodocker container. I generated it with 
```
docker run --rm repronim/neurodocker:0.7.0 generate docker -b centos:7 -p yum --ants version=2.3.1 --fsl version=6.0.3 > Dockerfile
```

After I buid it and ran it, I tested this simple minify command :
```
neurodocker-minify --container tominify --dirs-to-prune /opt --commands "file /opt/fsl-6.0.3/data/standard/MNI152_T1_*"
```

And it fails with (this is the end of the output) :
```
[...]
+ reprozip_cmd='/tmp/reprozip-miniconda/bin/reprozip trace -d /tmp/neurodocker-reprozip-trace --dont-identify-packages --overwrite file /opt/fsl-6.0.3/data/standard/MNI152_T1_*'
+ printf 'NEURODOCKER (in container): executing command: /tmp/reprozip-miniconda/bin/reprozip trace -d /tmp/neurodocker-reprozip-trace --dont-identify-packages --overwrite file /opt/fsl-6.0.3/data/standard/MNI152_T1_*\n'
[NEURODOCKER 2021-06-03 11:08:50,917 INFO]: + /tmp/reprozip-miniconda/bin/reprozip trace -d /tmp/neurodocker-reprozip-trace --dont-identify-packages --overwrite file /opt/fsl-6.0.3/data/standard/MNI152_T1_0.5mm.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_BigFoV_facemask.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_brain_mask_dil.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_brain_mask.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_brain.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_first_brain_mask.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_Hipp_mask_dil8.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_1mm.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_b0.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain_mask_deweight_eyes.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain_mask_dil1.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain_mask_dil.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain_mask.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_edges.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_eye_mask.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_LR-masked.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_skull.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_strucseg.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_strucseg_periph.nii.gz /opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_VentricleMask.nii.gz
[NEURODOCKER 2021-06-03 11:08:51,153 INFO]: /opt/fsl-6.0.3/data/standard/MNI152_T1_0.5mm.nii.gz:                        gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_BigFoV_facemask.nii.gz:          gzip compressed data, was "MNI152_T1_1mm_BigFoV_facemask.nii", last modified: Fri Feb  2 17:35:38 2018, max compression
/opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_brain_mask_dil.nii.gz:           gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_brain_mask.nii.gz:               gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_brain.nii.gz:                    gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_first_brain_mask.nii.gz:         gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_1mm_Hipp_mask_dil8.nii.gz:           gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_1mm.nii.gz:                          gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_b0.nii.gz:                       gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain_mask_deweight_eyes.nii.gz: gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain_mask_dil1.nii.gz:          gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain_mask_dil.nii.gz:           gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain_mask.nii.gz:               gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_brain.nii.gz:                    gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_edges.nii.gz:                    gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_eye_mask.nii.gz:                 gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_LR-masked.nii.gz:                gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm.nii.gz:                          gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_skull.nii.gz:                    gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_strucseg.nii.gz:                 gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_strucseg_periph.nii.gz:          gzip compressed data, from Unix
/opt/fsl-6.0.3/data/standard/MNI152_T1_2mm_VentricleMask.nii.gz:            gzip compressed data, from Unix
[NEURODOCKER 2021-06-03 11:08:51,260 INFO]: Uploading usage statistics is currently disabled
Please help us by providing anonymous usage statistics; you can enable this
by running:
    reprozip usage_report --enable
If you do not want to see this message again, you can run:
    reprozip usage_report --disable
Nothing will be uploaded before you opt in.
[NEURODOCKER 2021-06-03 11:08:51,260 INFO]: Configuration file written in /tmp/neurodocker-reprozip-trace/config.yml
Edit that file then run the packer -- use 'reprozip pack -h' for help
Traceback (most recent call last):
  File "/home/abonnet/.local/bin/neurodocker-minify", line 10, in <module>
    sys.exit(main())
  File "/home/abonnet/.local/lib/python3.7/site-packages/neurodocker/reprozip/gentle/trace.py", line 169, in main
    trace_and_prune(container=args.container, commands=args.commands, directories_to_prune=args.dirs_to_prune)
  File "/home/abonnet/.local/lib/python3.7/site-packages/neurodocker/reprozip/gentle/trace.py", line 96, in trace_and_prune
    raise RuntimeError("Failed: {}".format(result))
RuntimeError: Failed: Traceback (most recent call last):
  File "/tmp/_prune.py", line 69, in <module>
    main(yaml_file=args.config_file, directories_to_prune=args.dirs_to_prune)
  File "/tmp/_prune.py", line 18, in main
    raise RuntimeError(
RuntimeError: Not running in a Docker container. This script should only be used within a container.
```

I feel I just follow the instructions and was surprised to see it fail. Did I miss something ? Could this be centos7/python2 related ?

Any hep would be appreciated.

**Comment by kaczmarj** [comment]
@axlbonnet - thanks for the report. i'm able to reproduce this error. i wrote some checks in the minifying script to make sure that it was being run in a docker container, but it seems like those checks are not 100% reliable. i will update them.

i'm considering updating it to check in the way ti does now, and if it fails, it can ask the user is sure the script is being run in a container. the program can continue if the user responds yes.

**Comment by axlbonnet** [comment]
Thanks @kaczmarj ! 
Indeed it works if I disable this check.

Do you want to keep this issue opened until this check is updated ? Otherwise you (or I) can close it.

**Comment by kaczmarj** [comment]
great to hear. let's keep it open until a fix is in place.

**Comment by Remi-Gau** [comment]
@kaczmarj 
is it worth adding a once in a while CI workflow to run minify?
