### ISSUE TITLE
regression (on heudiconv): Missing required arguments: 'version'

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#466]
decided to update https://github.com/nipy/heudiconv/blob/master/Dockerfile produced using https://github.com/nipy/heudiconv/blob/master/utils/gen-docker-image.sh . Decision to update was to account for CLI change in `conda clean` which now leads to breaking docker image build and that issue was addressed in neurodocker.  So I changed script as 

```patch
diff --git a/utils/gen-docker-image.sh b/utils/gen-docker-image.sh
index 968a559..20f54e1 100755
--- a/utils/gen-docker-image.sh
+++ b/utils/gen-docker-image.sh
@@ -2,9 +2,10 @@
 
 set -eu
 
-VER=$(grep -Po '(?<=^__version__ = ).*' ../heudiconv/info.py | sed 's/"//g')
+thisd=$(dirname $0)
+VER=$(grep -Po '(?<=^__version__ = ).*' $thisd/../heudiconv/info.py | sed 's/"//g')
 
-image="kaczmarj/neurodocker:master@sha256:936401fe8f677e0d294f688f352cbb643c9693f8de371475de1d593650e42a66"
+image="kaczmarj/neurodocker:0.9.1"
 
 docker run --rm $image generate docker -b neurodebian:bullseye -p apt \
     --dcm2niix version=v1.0.20211006 method=source \

```
switching presumably from 0.4.2-3-gf7055a1 to 0.9.1 neurodocker!  As a result the script  calling

```
image="kaczmarj/neurodocker:0.9.1"

docker run --rm $image generate docker -b neurodebian:bullseye -p apt \
    --dcm2niix version=v1.0.20211006 method=source \
    --install git gcc pigz liblzma-dev libc-dev git-annex-standalone netbase \
    --copy . /src/heudiconv \
    --miniconda use_env=base conda_install="python=3.7 traits>=4.6.0 scipy numpy nomkl pandas" \
      pip_install="/src/heudiconv[all]" \
      pip_opts="--editable" \
    --entrypoint "heudiconv" \
> ../Dockerfile
```

errors out with

```
Status: Downloaded newer image for kaczmarj/neurodocker:0.9.1
Traceback (most recent call last):
  File "/opt/neurodocker/neurodocker/reproenv/renderers.py", line 213, in from_dict
    renderer.add_registered_template(method_or_template, **kwds)
  File "/opt/neurodocker/neurodocker/reproenv/renderers.py", line 366, in add_registered_template
    self.add_template(template=template, method=method)
  File "/opt/neurodocker/neurodocker/reproenv/renderers.py", line 264, in add_template
    template_method.validate_kwds()
  File "/opt/neurodocker/neurodocker/reproenv/template.py", line 133, in validate_kwds
    raise TemplateKeywordArgumentError(
neurodocker.reproenv.exceptions.TemplateKeywordArgumentError: Missing required arguments: 'version'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/neurodocker", line 33, in <module>
    sys.exit(load_entry_point('neurodocker', 'console_scripts', 'neurodocker')())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/neurodocker/neurodocker/cli/generate.py", line 431, in docker
    _base_generate(
  File "/opt/neurodocker/neurodocker/cli/generate.py", line 408, in _base_generate
    r = renderer.from_dict(renderer_dict)
  File "/opt/neurodocker/neurodocker/reproenv/renderers.py", line 215, in from_dict
    raise RendererError(
neurodocker.reproenv.exceptions.RendererError: Error on template 'miniconda'. Please see above for more information.

```

so from the second error I can guestimate it is miniconda lacking smth, some version for some package or itself... need to dig.  But it was working before so titled as regression (found no CHANGELOG and traversing github releases is too tedious to discover possible documented breakage)

**Comment by yarikoptic** [comment]
@kaczmarj any ideas on how to fix this and why `version` is now required?

**Comment by kaczmarj** [comment]
I think this version is about the version of miniconda. Using the latest version as default is not reproducible so now we ask for a version of miniconda. Although users are free to specify “latest”.

**Comment by djarecka** [comment]
@yarikoptic - have you tried to provide the version of miniconda? Do you still have the issue?
