### ISSUE TITLE
Can't run the latest version if installed from pypi

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/neurodocker#483]
Tried this

```bash
$ conda create --name neurodocker
$ conda activate neurodocker
$ conda install pip
$ pip install neurodocker
$ neurodocker --version
$ pip install neurodocker[dev]
$ neurodocker --version
```

```
$ python --version
Python 3.10.8
```

Getting this

```bash
Traceback (most recent call last):
  File "/home/remi/github/neurodocker/neurodocker/cli/minify/trace.py", line 26, in <module>
    client = docker.from_env()
AttributeError: module 'docker' has no attribute 'from_env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/remi/miniconda3/bin/neurodocker", line 33, in <module>
    sys.exit(load_entry_point('neurodocker', 'console_scripts', 'neurodocker')())
  File "/home/remi/miniconda3/bin/neurodocker", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/remi/miniconda3/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/remi/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/remi/github/neurodocker/neurodocker/cli/cli.py", line 24, in <module>
    from neurodocker.cli.minify.trace import minify
  File "/home/remi/github/neurodocker/neurodocker/cli/minify/trace.py", line 29, in <module>
    except docker.errors.DockerException:
AttributeError: module 'docker' has no attribute 'errors'
```

**Comment by Remi-Gau** [comment]
suspect this is related to something specific to my system (docker install?)

so will close this for now as I am assuming this is not a neurodocker related issue.
